apiVersion : apps/v1
kind: Deployment
metadata:
  name: "dotnetapptest-5f46"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "dotnetapptest-5f46"
  template:
    metadata:
      labels:
        app: "dotnetapptest-5f46"
    spec:
      containers:
        - name: "dotnetapptest-5f46"
          image: "chenxizhangacr.azurecr.io/dotnetapptest"
          ports:
          - containerPort: 80